name: Main Preview

on:
  push:
    branches: [main]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
        shell: bash
      - name: Build Storybook
        run: npx storybook build
        shell: bash
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2.22.35
          arch: amd64
      - name: Upload to S3
        uses: gravity-ui/preview-upload-to-s3-action@v1
        with:
          src-path: storybook-static
          dest-path: /date-components/main/
          s3-key-id: ${{ secrets.STORYBOOK_S3_KEY_ID }}
          s3-secret-key: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
